# NOTE: ${user.home}/com.platformadmin.minimalplugin.build.properties is loaded prior to this
# and can be used to override these defaults.

plugin.name = MinimalPlugin
plugin.vendor = Paul Homes
plugin.copyright.years = 2026
plugin.copyright = ${plugin.copyright.years} ${plugin.vendor}
plugin.version = 0.1
plugin.jar.name = minimal-plugin.jar

sas94m9.sashome=/opt/sas94m9/sashome
sas94m9.vjr.plugins=${sas94m9.sashome}/SASVersionedJarRepository/eclipse/plugins
sas94m9.sasmc.dir=${sas94m9.sashome}/SASManagementConsole/9.4